### ISSUE TITLE
What about a new release? There's a pdb statement in 1.2.5

### ISSUE THREAD

**Issue by idgserpro** [collective/iw.rejectanonymous#12]
It was removed in https://github.com/collective/iw.rejectanonymous/blob/5e0f52d06cbf5d3b96049dbe3a3dafe26498e8cf/iw/rejectanonymous/utils.py but a new release is needed, otherwise you have to pin for 1.2.4.

**Comment by ale-rt** [comment]
Before making a new release,  I would also consider merging https://github.com/collective/iw.rejectanonymous/pull/11 if possible.
BTW @idgserpro would you like to review https://github.com/collective/iw.rejectanonymous/pull/11?

**Comment by idgserpro** [comment]
By reviewing this PR, I see no problem with it, but unfortunately I'm not that versed in Plone 5 to tell if could have any security implications I'm not aware of (specially since I don't know all possibilities that `++unique++` could have in a Plone Site). If there are any sources about why these modifications are needed from Plone 5.2.2 onwards, at least in the commit message, would be a nice addition.

I was asking for a immediate release because just by adding iw.rejectanonymous in a buildout gets a broken package with a pdb statement.

**Comment by ale-rt** [comment]
@tdesvenain @jaroel @gotcha @ebrehault I see you are maintainer on PyPI.
Can somebody do a release, please?
As an alternative you can add me as maintainer. 
My username on PyPI is `alert` in that way I can do a release myself.

It is also a good idea to add the `collective` user as maintainer of the package (see https://pypi.org/user/collective/).

**Comment by ale-rt** [comment]
Ping: @tdesvenain @jaroel @gotcha @ebrehault ^

**Comment by jaroel** [comment]
I've sent an invite. Have fun @ale-rt !

**Comment by ale-rt** [comment]
1.2.6 is on PyPI https://pypi.org/project/iw.rejectanonymous/#history
